# Site settings
title: How to Build Java Applications Today?
description: >- # this means to ignore newlines until "baseurl:"
  In Java today, we're all novices somewhere. Let's share some advice!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.howjavatoday.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: GFM
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
# github: [metadata]

# Exclude from processing.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - etc
